name: _ci

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Release
      # https://github.com/softprops/action-gh-release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: main
        files: target/debug/gitopolis
