name: _ci
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/debug/gitopolis"
        token: ${{ secrets.GITHUB_TOKEN }}
