name: _release
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: cargo install -f cross
#    - name: Build
#      run: cargo build --verbose --release
    - name: Build-win
      run: cross build --target x86_64-pc-windows-gnu
#    - name: Test
#      run: cargo test --verbose --release
    - name: Package
      run: tar -czvf gitopolis.tar.gz target/*
    - name: Publish
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        artifacts: gitopolis.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}
