name: _release
on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: cargo install -f cross
    - name: Build-linux
      run: cross build --target x86_64-unknown-linux-gnu --release
    - name: Build-win
      run: cross build --target x86_64-pc-windows-gnu --release
    - name: Package Linux
      run: tar -czvf gitopolis.tar.gz -C target/x86_64-unknown-linux-gnu/release/ gitopolis
    - name: Package Windows
      run: zip gitopolis.zip target/x86_64-pc-windows-gnu/release/gitopolis.exe
    - name: Publish
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        artifacts: gitopolis.tar.gz,gitopolis.zip
        token: ${{ secrets.GITHUB_TOKEN }}
